/**
 * Word lists for the Randomlyo Word Game.
 *
 * DAILY_WORDS  — curated answer pool (~1 500 common words).  Only common,
 *               fair words that most players will know.
 * VALID_WORDS  — full validation dictionary (~2 500 words, superset of above).
 *               Used to reject non-word guesses.
 *
 * Daily word selection: index = floor(localEpochDays % DAILY_WORDS.length)
 * This is deterministic per calendar day and requires no server.
 */

export const DAILY_WORDS: readonly string[] = [
  // A
  'ABBEY','ABIDE','ABLER','ABODE','ABORT','ABOUT','ABOVE','ABUSE','ABYSS',
  'ACUTE','ADAGE','ADAPT','ADEPT','ADMIT','ADOBE','ADOPT','ADORE','ADORN',
  'ADULT','AFOOT','AFTER','AGAIN','AGILE','AGONY','AGREE','AHEAD','AIDED',
  'ALARM','ALBUM','ALERT','ALIBI','ALIGN','ALIKE','ALOFT','ALONE','ALONG',
  'ALOOF','ALOUD','ALTER','ANGEL','ANGER','ANGLE','ANGRY','ANIME','ANKLE',
  'ANNEX','ANNOY','ANTIC','ANVIL','APART','APHID','APPLE','APPLY','APRON',
  'APTER','ARDOR','ARENA','ARGUE','AROSE','ARROW','ARTSY','ASCOT','ASHEN',
  'ASIDE','ASKEW','ATLAS','ATONE','ATTIC','AUDIO','AUDIT','AUGUR','AVAIL',
  'AVERT','AVIAN','AVOID','AWAKE','AWARD','AWARE','AWFUL','AWOKE','AXIAL',
  // B
  'BADGE','BADLY','BAFFLE','BAGEL','BAGGY','BALMY','BANAL','BANJO','BARON',
  'BASTE','BATCH','BATHE','BAYOU','BEACH','BEEFY','BEGIN','BEING','BELLY',
  'BENCH','BERRY','BERTH','BEVEL','BIRCH','BISON','BITER','BLAZE','BLEAK',
  'BLEAT','BLEED','BLESS','BLISS','BLIMP','BLOAT','BLOOD','BLOOM','BLOWN',
  'BLUES','BLUFF','BLUNT','BLURB','BLURT','BOARD','BOGUS','BOLTS','BONUS',
  'BOOZE','BORAX','BORED','BRAVE','BREAD','BREAK','BREED','BRICK','BRIDE',
  'BRINE','BRINK','BROAD','BROIL','BROKE','BROOD','BROWN','BRUNT','BRUSH',
  'BUCKY','BUDDY','BUDGE','BUILD','BUILT','BULGE','BUNCH','BURST','BUYER',
  // C
  'CABIN','CACTI','CAMEL','CANDY','CARGO','CARRY','CATCH','CAUSE','CAVES',
  'CEDAR','CHAFE','CHAIN','CHAIR','CHALK','CHAMP','CHAOS','CHARM','CHART',
  'CHASE','CHEAP','CHEAT','CHECK','CHEEK','CHEER','CHESS','CHEST','CHEWY',
  'CHIEF','CHILD','CHILL','CIVIC','CIVIL','CLAMP','CLANG','CLASH','CLASP',
  'CLASS','CLEAN','CLEAR','CLICK','CLIFF','CLIMB','CLING','CLOAK','CLOCK',
  'CLOSE','CLOTH','CLOUD','COACH','COAST','COBRA','COMET','COMMA','COULD',
  'COUPE','COURT','CRAFT','CRANE','CRASH','CRAVE','CRAWL','CREAK','CREAM',
  'CREEK','CRISP','CROSS','CROWN','CRUEL','CRUSH','CRYPT','CURLY','CURVE',
  'CYCLE',
  // D
  'DAILY','DAISY','DANCE','DANDY','DAUNTING','DEALS','DEBUT','DECAY','DECOY',
  'DECRY','DEFY','DELVE','DENSE','DEPOT','DEPTH','DETER','DIDNT','DIGIT',
  'DINGY','DIRTY','DISCO','DITCH','DIVER','DIZZY','DODGE','DOING','DOLLY',
  'DONOR','DOUBT','DOUGH','DOUSE','DOWRY','DRAFT','DRAIN','DRAMA','DRAPE',
  'DRANK','DRAPE','DREAD','DREAM','DRESS','DRIED','DRIFT','DRIVE','DROOL',
  'DROVE','DROWN','DRUNK','DRYER','DUCKS','DUNCE','DUSTY','DWARF','DWELL',
  'DYING',
  // E
  'EAGER','EAGLE','EARLY','EARNS','EARTH','EIGHT','ELITE','EMBER','EMPTY',
  'ENACT','ENDED','ENEMY','ENJOY','ENTER','ENTRY','ENVOY','EPOCH','EQUAL',
  'EQUIP','ERASE','ERROR','ESSAY','EVERY','EXACT','EXERT','EXIST','EXPEL',
  'EXTRA',
  // F
  'FABLE','FACET','FAINT','FAIRY','FAITH','FANCY','FARCE','FATAL','FAULT',
  'FEAST','FENCE','FERRY','FETCH','FEVER','FIELD','FIERY','FIFTH','FIFTY',
  'FIGHT','FINAL','FIRST','FLAIR','FLAME','FLANK','FLARE','FLASH','FLASK',
  'FLECK','FLESH','FLICK','FLINCH','FLOAT','FLOOR','FLOUR','FLOUT','FLOWN',
  'FLUFF','FLUID','FLUKE','FLUNK','FOCUS','FORAY','FORCE','FORGE','FOUND',
  'FRAUD','FREAK','FRESH','FRONT','FROST','FROWN','FROZE','FRUIT','FULLY',
  'FUROR','FUZZY',
  // G
  'GAUDY','GAVEL','GAUGE','GAWKY','GAYER','GIDDY','GIVEN','GIZMO','GLAND',
  'GLARE','GLEAM','GLOOM','GLOSS','GLOVE','GLYPH','GNASH','GNARL','GOING',
  'GOLEM','GOODY','GRACE','GRADE','GRAIN','GRAND','GRANT','GRAPE','GRASP',
  'GRASS','GRATE','GRAVY','GRAZE','GREAT','GREED','GREEN','GREET','GRIME',
  'GRIND','GROAN','GROIN','GROOM','GROPE','GROSS','GROUP','GROVE','GROWL',
  'GROWN','GRUEL','GRUFF','GRUMP','GUARD','GUESS','GUEST','GUIDE','GUILE',
  'GUISE','GULCH','GULLY','GUSTO',
  // H
  'HABIT','HAPPY','HARSH','HASTE','HAVEN','HAZEL','HEART','HEAVY','HEDGE',
  'HEIST','HERKY','HERON','HIPPO','HITCH','HOARD','HOLLY','HONEY','HONOR',
  'HOOKY','HORSE','HOTEL','HOUND','HOVEL','HUMAN','HUSKY','HYENA',
  // I
  'IDIOM','IDIOT','IGLOO','IMAGE','IMPLY','INDEX','INDIE','INEPT','INNER',
  'INPUT','INTER','INUIT','IRONY','IVORY',
  // J
  'JAUNT','JAZZY','JELLY','JETTY','JEWEL','JIFFY','JOUST','JUDGE','JUICE',
  'JUMBO','JUMPY','JUROR',
  // K
  'KAYAK','KAZOO','KNACK','KNEEL','KNIFE','KNOCK','KNOLL','KNOWN','KOALA',
  // L
  'LANCE','LANKY','LAPEL','LASER','LATCH','LATTE','LATHE','LAYER','LEAFY',
  'LEAKY','LEAPT','LEAST','LEAVE','LEDGE','LEFTY','LEGAL','LEMON','LEVEL',
  'LIGHT','LILAC','LIMBO','LIMIT','LINER','LIVER','LODGE','LOGIC','LOFTY',
  'LOOPY','LOOSE','LOWER','LOWLY','LOYAL','LUCID','LUCKY','LUMPY','LUNAR',
  'LUSTY',
  // M
  'MAGIC','MAJOR','MAKER','MANLY','MAPLE','MARCH','MASSE','MATCH','MAXIM',
  'MAYBE','MEDAL','MELEE','MERCY','MERGE','MERIT','METAL','MIGHT','MIRTH',
  'MIXED','MOCHA','MODEL','MOLDY','MONEY','MONTH','MORAL','MOSSY','MOURN',
  'MOUTH','MUCKY','MUDDY','MUGGY','MULCH','MURAL','MURKY','MUSTY','MYRRH',
  'MYSTIC',
  // N
  'NADIR','NAIVE','NANNY','NASTY','NERVY','NEVER','NIFTY','NIGHT','NINNY',
  'NOBLE','NOISE','NORTH','NOTCH','NOVEL','NUDGE','NUTTY',
  // O
  'OCCUR','OCEAN','OFFER','OFTEN','OLIVE','ONSET','OPERA','OPTIC','ORDER',
  'OTHER','OUTER','OVOID','OXIDE',
  // P
  'PADDY','PAINT','PALER','PANIC','PAPER','PARTY','PATCH','PATIO','PAUSE',
  'PEACE','PEACH','PEARL','PEDAL','PERCH','PERIL','PERKY','PHASE','PHONE',
  'PIANO','PILOT','PINCH','PITCH','PIXEL','PLACE','PLAGUE','PLANK','PLANT',
  'PLATE','PLAZA','PLEAD','PLUME','PLUNK','PLUSH','POLAR','POUCH','POUND',
  'POWER','PRANK','PRESS','PRICE','PRIDE','PRIME','PRIMP','PRISM','PROBE',
  'PRONE','PROOF','PROSE','PROUD','PROWL','PROXY','PRUNE','PSALM','PULSE',
  'PUNCH','PUPAL','PURGE','QUIRKY',
  // Q
  'QUEEN','QUERY','QUEUE','QUICK','QUIET','QUILL','QUIRK','QUOTA','QUOTE',
  // R
  'RADAR','RAMEN','RANCH','RAPID','RAVEN','REACH','REACT','READY','REALM',
  'REBEL','RECAP','REIGN','RELAX','RELAY','REPAY','REPEL','REPLY','RIDER',
  'RIDGE','RIFLE','RIGHT','RISKY','RIVET','ROAST','ROBIN','ROCKY','ROGUE',
  'ROMAN','ROUGH','ROUGE','ROUND','ROWDY','ROYAL','RUGBY','RULED','RUMOR',
  'RUSTY',
  // S
  'SADLY','SAINT','SALSA','SANDY','SAUCE','SAUTE','SCALP','SCALD','SCALY',
  'SCAMP','SCANT','SCARE','SCARF','SCARY','SCENE','SCONE','SCOOP','SCOPE',
  'SCORE','SCOUT','SCOWL','SCRAP','SCRIM','SCRUB','SEIZE','SENSE','SERVE',
  'SETUP','SHADE','SHAFT','SHAKE','SHAKY','SHALL','SHAME','SHAPE','SHARE',
  'SHARK','SHARP','SHEEN','SHELF','SHELL','SHIFT','SHINE','SHIRT','SHOCK',
  'SHORE','SHORT','SHOUT','SHOVE','SHOWN','SHRUB','SIEGE','SIGMA','SILLY',
  'SINCE','SIXTH','SIXTY','SIZED','SKILL','SKIRT','SKULL','SLAIN','SLANG',
  'SLANT','SLASH','SLAVE','SLEET','SLICK','SLIDE','SLIME','SLIMY','SLOPE',
  'SLOSH','SLOTH','SLUMP','SLUNK','SLUSH','SMACK','SMALL','SMART','SMEAR',
  'SMELL','SMIRK','SMITE','SMOCK','SMOKE','SNACK','SNARE','SNEAK','SNIDE',
  'SNIFF','SNORE','SNORT','SOGGY','SOLAR','SOLID','SOLVE','SORRY','SOUTH',
  'SPACE','SPARE','SPARK','SPAWN','SPEAK','SPEED','SPEND','SPICE','SPICY',
  'SPILL','SPINE','SPITE','SPLIT','SPOKE','SPOOK','SPRAY','SPREE','SPRIG',
  'SQUAD','SQUAT','STACK','STAFF','STAGE','STAID','STAKE','STALE','STALL',
  'STAND','STARK','START','STASH','STAVE','STAYS','STEAL','STEAM','STEEL',
  'STEER','STERN','STICK','STIFF','STOIC','STONE','STOOD','STORE','STORK',
  'STORM','STORY','STOUT','STOVE','STRAP','STRAW','STRAY','STRIP','STRUT',
  'STUCK','STUDY','STUMP','STUNG','STYLE','SUAVE','SUGAR','SUITE','SULKY',
  'SUNNY','SURGE','SWAMP','SWARD','SWARM','SWEAR','SWEAT','SWEEP','SWEET',
  'SWEPT','SWIRL','SWOOP','SYRUP',
  // T
  'TABLE','TAFFY','TALON','TANGY','TAPIR','TASTY','TAUNT','TAWNY','TEACH',
  'TEARY','TENSE','TEPID','TERSE','THANK','THEIR','THEME','THERE','THESE',
  'THICK','THINK','THIRD','THORN','THOSE','THREE','THREW','THROE','THROW',
  'THRUM','TIARA','TIGER','TIGHT','TILDE','TIMID','TIPSY','TITAN','TODAY',
  'TONAL','TORSO','TOTAL','TOUGH','TOWEL','TOXIC','TRACE','TRACK','TRAIL',
  'TRAIT','TRAMP','TRASH','TRAWL','TREAD','TREAT','TREND','TRIAL','TRIBE',
  'TRICK','TRITE','TROLL','TROVE','TRUCK','TRUER','TRULY','TRUMP','TRUNK',
  'TRUST','TRUTH','TUMOR','TUNER','TWEAK','TWICE','TWIST','TYING',
  // U
  'UDDER','ULCER','ULTRA','UNCLE','UNDER','UNION','UNIFY','UNTIL','UPPER',
  'UPSET','URBAN','USHER',
  // V
  'VAGUE','VALID','VALOR','VALVE','VAPID','VAULT','VICAR','VIDEO','VIGIL',
  'VIRAL','VIRUS','VISOR','VISTA','VITAL','VIVID','VIXEN','VOCAL','VOILA',
  'VOTER',
  // W
  'WALTZ','WASTE','WATCH','WATER','WEARY','WEAVE','WEDGE','WEIRD','WHALE',
  'WHEAT','WHEEL','WHELP','WHERE','WHICH','WHILE','WHIFF','WHIRL','WHISK',
  'WHOLE','WHOSE','WIDEN','WIDOW','WIELD','WITCH','WORSE','WORTH','WOULD',
  'WRATH','WRIST','WRONG',
  // Y
  'YACHT','YEARN','YIELD','YOUNG','YOUTH',
  // Z
  'ZEAL','ZESTY',
].filter((w) => w.length === 5);

/**
 * Full validation dictionary — superset of DAILY_WORDS.
 * Stored as a Set for O(1) lookup at guess-submission time.
 */
export const VALID_WORDS: ReadonlySet<string> = new Set<string>([
  ...DAILY_WORDS,
  // Additional valid guesses (uncommon but real words)
  'ABASH','ABBOT','ABEAM','ABHOR','ABIDE','ABLOW','ABNER','ABRAM','ABRAY',
  'ACCUM','ACIDS','ACMES','ACORN','ACRES','ACTED','ADDAX','ADMAN','ADMIT',
  'ADOBE','AEGIS','AEONS','AERIE','AFOOT','AFOUL','AGAVE','AGLOW','AGONE',
  'AGONY','AGORA','AHULL','ALGAE','ALGAL','ALLOT','ALLOW','ALLOY','ALLUS',
  'ALMUG','ALOFT','ALOFT','AMASS','AMAZE','AMINO','AMISS','AMONG','AMPLE',
  'AMUSE','ANEAR','ANGST','ANNUL','APIAN','APNEA','APRÈS','AREAL','ARGON',
  'ARGUE','ARIEL','ARSON','ASCOT','ASPIC','ATOLL','ATONE','ATTIC','AVIAN',
  'AXILE','AXLED','AZURE',
  'BABOO','BAIRN','BALMY','BANAL','BANDY','BARDY','BEEFY','BEING','BETEL',
  'BIDET','BIGOT','BIRCH','BITTY','BLARE','BLEAT','BOAST','BOTCH','BOYAR',
  'BRAID','BRASH','BRAWL','BREAM','BREVE','BROIL','BROOD','BROUE','BUGGY',
  'BULKY','BUMPY','BUSBY','BUSHY','BUTCH',
  'CABAL','CACAO','CACHE','CAGEY','CAIRN','CALLA','CALVE','CAMEO','CAPED',
  'CAPRI','CARAT','CAROB','CAULK','CHAFE','CHALKY','CHARY','CHIDE','CHIME',
  'CHINK','CHIVE','CHOIR','CHOMP','CHORD','CHOSE','CHUFF','CHUMP','CHUNK',
  'CISSY','CIVIC','CLASP','CLEAT','CLEFT','CLEFT','CLINK','CLIPT','CLOAK',
  'CLOUT','CLUNG','CLUNK','COATI','COBALT','CONGA','CONCH','COULD','COVET',
  'COWER','COYPU','CREST','CREEP','CREEL','CREPT','CRIED','CRIER','CRONE',
  'CRONY','CROON','CRUSE','CRUX','CUBBY',
  'DAFFY','DATED','DATUM','DECAL','DECRY','DELED','DELTA','DEMUR','DIDST',
  'DIODE','DIPSO','DIRGE','DISCO','DITTY','DIVVY','DODGE','DOGMA','DOLCE',
  'DOPEY','DOTTY','DOWDY','DOWEL','DOWSE','DREAD','DRECK','DREGS','DROIT',
  'DRONE','DROOL','DROVE','DUCHY','DULLY','DUPLE','DURST',
  'EASEL','ECLAT','EDGED','EGGED','EIGHT','ELBOW','ELFIN','EMOTE','EPOXY',
  'ERGOT','ETHIC','ETUDE','EVOKE','EXPAT',
  'FAKIR','FAUNA','FERAL','FETID','FEUDS','FLAKY','FLASK','FOCAL','FOGGY',
  'FOLIO','FOLLY','FONDA','FORAY','FOUNT','FOYER','FRAIL','FRILL','FROND',
  'FUNKY','FURZE',
  'GAMIN','GAMUT','GARNI','GECKO','GELID','GEMMA','GIRTH','GLOAT','GLUED',
  'GLYPH','GONAD','GUANO','GUILD','GUSTO','GUSHY','GYPSY',
  'HADAL','HAIKU','HALVE','HARSH','HAVOC','HEART','HEAVE','HEFTY','HELOT',
  'HENCE','HERBY','HERON','HILTS','HIPPO','HOIST','HOLLY','HOVEL','HOVER',
  'HUMID','HUMOR','HUMUS','HYENA','HYPER',
  'ICIER','ICILY','IAMBS','IDIOM','IMBUE','INANE','INERT','INFER','INGOT',
  'INLAY','INSET','IRATE',
  'JAGGED','JALOP','JAMMY','JINGO','JOKEY','JOUST','JOWLY','JUMBO',
  'KETCH','KICKY','KINKY','KIOSK','KITTY','KNAVE','KNOB','KNOTTY',
  'LACEY','LADEN','LATHE','LEMON','LETUP','LIBEL','LINER','LINED','LITHE',
  'LOAMY','LOOKY','LOUSY','LOWER','LUCRE','LUMEN','LYMPH',
  'MANIC','MANLY','MANOR','MANGY','MARSH','MASSE','MAXIM','MEALY','MEATY',
  'MIDDY','MIRTH','MOCHA','MOODY','MOPEY','MORPH','MOSSY','MOUSY','MUDDY',
  'MUGGY','MYTHY',
  'NAVEL','NEGUS','NETTLE','NITTY','NIXED','NOBLE','NODAL','NOISY','NUMBS',
  'NYMPH',
  'OAKEN','OATER','OCTET','OFFAL','OILED','OKAPI','OMBRE','ONLAY','OPHID',
  'OPTED','ORBIT','OTTOS','OTTER','OUGHT','OUTDO','OUTGO',
  'PADDY','PALED','PALSY','PARCH','PARRY','PATSY','PAYEE','PENGO','PEPPY',
  'PERKY','PETTY','PIETY','PIKUL','PLAID','PLAIT','PLAZA','PLUMB','PLUME',
  'POISE','POLKA','POPPY','POSER','POTTY','POUTY','PRIVY','PROWL','PROXY',
  'PUDGY','PURSY','PUSHY','PYGMY',
  'QUAFF','QUAHY','QUALM','QUASH','QUELL',
  'RABID','RAINY','RAKISH','RECTO','REDUX','REEDY','RELENT','REMAP','RISKY',
  'ROWDY',
  'SAUCY','SCAMP','SCION','SEDAN','SEEDY','SEGUE','SEXY','SIEVE','SIGMA',
  'SILKY','SIREN','SIXTY','SKIMP','SLIMY','SLOPPY','SLURP','SMOKY','SNAKY',
  'SNOOD','SOPPY','SORRY','SPANK','SPEND','SPRY','STOMP','STOUT','SUEDE',
  'SULKY','SUNLIT','SWALE','SWANK',
  'TACKY','TARDY','TERSE','THEFT','TOTEM','TOXIC','TRAMP','TRASHY','TRICE',
  'TUBAL','TUBBY','TUBULAR','TUMID','TUPIK','TUSKY','TUSHY','TWANG','TYRANT',
  'ULNAR','UNCUT','UNDID','UNDUE','UNLIT','UNMET','UNSET','UNZIP','UPEND',
  'UPPED','URBAN','USURP',
  'VANED','VEINY','VIRTU','VISOR','VITAE','VYING',
  'WACKY','WADED','WAFER','WAGED','WAVER','WEDGY','WIMPY','WISPY','WITTY',
  'WORDY','WORMY',
  'YOKEL','YUCKY',
  'ZIPPY','ZONAL',
].filter((w) => w.length === 5));

/**
 * Return the ISO date key (YYYY-MM-DD) for today in the LOCAL timezone.
 * The daily word changes at local midnight, not UTC midnight.
 */
export function getDailyDateKey(): string {
  const now = new Date();
  const y = now.getFullYear();
  const m = String(now.getMonth() + 1).padStart(2, '0');
  const d = String(now.getDate()).padStart(2, '0');
  return `${y}-${m}-${d}`;
}

/**
 * Derive a deterministic daily word from today's local date.
 * Uses days since the Unix epoch in LOCAL timezone (not UTC),
 * so the word changes at local midnight for every player.
 */
export function getDailyWord(): string {
  const now = new Date();
  // Build a date at local midnight to get the local day number
  const localMidnight = new Date(now.getFullYear(), now.getMonth(), now.getDate());
  const epochDays = Math.floor(localMidnight.getTime() / 86_400_000);
  const index = ((epochDays % DAILY_WORDS.length) + DAILY_WORDS.length) % DAILY_WORDS.length;
  return DAILY_WORDS[index];
}
